# Copyright 2023 Chris Croome
#
# This file is part of the Webarchitects logrotate Ansible role.
#
# The Webarchitects logrotate Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects logrotate Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects logrotate Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Logrotate
  block:

    - name: Verify variables that start with logrotate_
      ansible.builtin.include_tasks: verify.yml
      when:
        - logrotate_verify is defined
        - logrotate_verify | bool

    - name: Find all files in /etc/logrotate.d
      ansible.builtin.find:
        paths: /etc/logrotate.d
      register: logrotate_find

    - name: Debug the results of find
      ansible.builtin.debug:
        var: logrotate_find
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    # - name: Ensure that all files in /etc/logrotate.d are mode 0644

    # - name: Check logrotate config using /usr/sbin/logrotate -d for all files

  when:
    - logrotate is defined
    - logrotate | bool
  tags:
    - logrotate
...
